version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  userservise:
    image: aogorokhov/userservise
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  secondservise:
    image: aogorokhov/secondservise
    ports:
      - "3001:3001"
    depends_on:
      - userservise